version: '3'
services:
  mongodb:
    image: mongodb-image
    ports: 
      - 27017:27017

  java-app:
    image: javaapp
    depends_on:
      - mongodb
    networks:
      - app-network
  
  react-app:
    image: reactapp
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network: